CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    selleruid INTEGER NOT NULL,
    desc TEXT,
    price REAL NOT NULL--,
    --image1 VARCHAR(255)
);

INSERT INTO products (name, selleruid, desc, price) VALUES
('Apple MacBook Air', 1, 'Lightweight laptop with M1 chip', 999.99),
('Google Pixel 7', 1, 'Google smartphone with excellent camera', 599.99),
('Bose QuietComfort 45', 1, 'Noise-canceling headphones with premium sound', 329.99),
('Microsoft Surface Pro 9', 1, '2-in-1 laptop with detachable keyboard', 1099.99),
('Amazon Echo Dot', 1, 'Smart speaker with Alexa voice assistant', 49.99),
('Sony PlayStation 5', 1, 'Next-gen gaming console with immersive graphics', 499.99),
('Nintendo Switch OLED', 1, 'Portable gaming console with vibrant display', 349.99),
('Logitech MX Master 3', 1, 'Ergonomic wireless mouse for productivity', 99.99),
('HP Envy 6055e', 1, 'All-in-one printer for home use', 149.99),
('Fitbit Charge 5', 1, 'Fitness tracker with health monitoring features', 129.99),
('Canon EOS R6', 1, 'Full-frame mirrorless camera for professionals', 2499.99),
('DJI Mini 3 Pro', 1, 'Compact drone with 4K video recording', 759.99),
('Samsung 55" QLED TV', 1, 'Smart TV with stunning picture quality', 799.99),
('Anker PowerCore 26800', 1, 'Portable charger with high capacity', 59.99),
('Razer BlackWidow V3', 1, 'Mechanical gaming keyboard with RGB lighting', 139.99),
('Corsair Vengeance RGB Pro', 1, 'High-performance RAM for gaming PCs', 89.99),
('Seagate 2TB External HDD', 1, 'Portable hard drive for data storage', 69.99),
('Asus ROG Strix G15', 1, 'Gaming laptop with powerful specs', 1499.99),
('HyperX Cloud II', 1, 'Gaming headset with virtual 7.1 surround sound', 99.99),
('Acer Predator Helios 300', 1, 'Gaming laptop with 15.6" Full HD display', 1099.99),
('JBL Charge 5', 1, 'Portable Bluetooth speaker with long battery life', 149.99),
('Xiaomi Redmi Note 11', 1, 'Budget smartphone with quad-camera setup', 199.99),
('Lenovo ThinkPad X1 Carbon', 1, 'Ultralight business laptop with 14" display', 1299.99),
('SteelSeries Arctis 7', 1, 'Wireless gaming headset with retractable mic', 149.99),
('Asus ZenBook 14', 1, 'Ultra-thin laptop with 14" Full HD display', 699.99),
('Samsung Galaxy Watch 4', 1, 'Smartwatch with built-in GPS and heart rate monitoring', 299.99),
('Beats Solo Pro', 1, 'Wireless headphones with active noise cancellation', 299.99),
('Microsoft Xbox Series X', 1, 'Next-gen gaming console with ray tracing', 599.99),
('Dell Inspiron 15 5000', 1, 'Budget laptop with 15.6" HD display', 399.99),
('Sony WH-1000XM4', 1, 'Wireless headphones with industry-leading noise cancellation', 349.99),
('HP Pavilion Gaming Desktop', 1, 'Pre-built gaming PC with AMD Ryzen processor', 999.99),
('Logitech G502 Lightspeed', 1, 'Wireless gaming mouse with 11 programmable buttons', 149.99),
('Apple iPad Air', 1, 'Tablet with 10.9" Liquid Retina display', 599.99),
('Google Nest Hub', 1, 'Smart display with Google Assistant', 99.99),
('Razer Blade 15', 1, 'Gaming laptop with 15.6" Quad HD display', 1999.99),
('Canon EF 50mm f/1.8', 1, 'Prime lens for Canon DSLR cameras', 125.99),
('Amazon Fire TV Stick', 1, 'Streaming device with Alexa voice remote', 39.99),
('Jabra Elite 85h', 1, 'Wireless headphones with advanced noise cancellation', 299.99),
('GoPro HERO11 Black', 1, 'Action camera with advanced stabilization', 499.99);

